/**
 * Dropdown validation for the "Parameter Add" tab — every dropdown listed
 * below is generated by this script (no manual Data > Data validation setup
 * needed), matched by COLUMN NAME (header text), not column position. You
 * can reorder, insert, or rename supporting columns freely; only the header
 * text of the columns this script cares about has to match (case- and
 * whitespace-insensitive), including "Range Type" (renamed from
 * "Material Range" — the old name is kept as a fallback alias below so nothing
 * breaks if an older copy of the sheet still says "Material Range").
 *
 * "Grouping" is intentionally NOT handled here — you're building that
 * dropdown yourself.
 *
 * Two kinds of dropdown:
 *  - STATIC (Parameter Category, Parameter type, Default state, Composite
 *    type, Value relationships, Range Type, Expression Type): a fixed list
 *    of options, applied once to a generous row range (2:2000) so it also
 *    works on rows you haven't typed into yet.
 *  - CASCADING (Data type): depends on the Parameter type value in the same
 *    row — matches the Float/Integer/Text/Float2/Boolean/Multiple boolean
 *    values/Material/Contour/Style matrix from your screenshots. Recomputed
 *    live by onEdit() whenever Parameter type changes, including on a
 *    fill-handle drag across many rows (Sheets fires onEdit once for the
 *    whole dragged range, not once per row — handled explicitly below so a
 *    multi-row drag doesn't leave rows 2..N unvalidated).
 *
 * Install: Extensions > Apps Script > select all > paste this file > Save,
 * then run setupAllDropdowns() once from the Run menu (it will ask you to
 * authorize the first time). After that, onEdit runs automatically.
 *
 * Re-run setupAllDropdowns() any time you add, rename, or reorder the
 * columns this script reads — it re-resolves every column by header text
 * from scratch, so it's always safe to re-run.
 */

const DATA_SHEET_NAME = 'Parameter Add';
const LAST_SETUP_ROW = 2000; // static dropdowns are pre-applied through this row

// Header text this script looks for -> internal key. Matched case- and
// whitespace-insensitively via normHeader(). First matching alias wins.
const FIELDS = {
  paramCategory:      ['Parameter Category'],
  paramType:          ['Parameter type'],
  dataType:           ['Data type'],
  defaultState:       ['Default state'],
  compositeType:      ['Composite type'],
  valueRelationships: ['Value relationships'],
  rangeType:          ['Range Type', 'Material Range'],
  expressionType:     ['Expression Type']
};

// Static dropdown option lists, per your screenshots.
const STATIC_OPTIONS = {
  paramCategory:      ['Global', 'Local'],
  paramType:          ['Float', 'Float2', 'Integer', 'Text', 'Boolean', 'Multiple boolean values', 'Material', 'Contour', 'Style'],
  defaultState:       ['Value', 'Formula'],
  compositeType:      ['Range', 'Options'],
  valueRelationships: ['Outside', 'Within'],
  rangeType:          ['Select', 'Condition'],
  expressionType:     ['Reference', 'Condition']
};

// Cascading: Parameter type -> valid Data types, per your screenshot matrix.
const TYPE_DATATYPE_MAP = {
  'float':                   ['Options', 'Interval', 'Range', 'Advanced Formula', 'Formula', 'Fixed Value'],
  'integer':                 ['Options', 'Interval', 'Range', 'Advanced Formula', 'Formula', 'Fixed Value'],
  'text':                    ['Unlimited', 'Options', 'Advanced Formula', 'Formula', 'Fixed Value'],
  'float2':                  ['Unlimited', 'Advanced Formula', 'Formula'],
  'boolean':                 ['Unlimited', 'Fixed Value'],
  'multiple boolean values': ['Unlimited', 'Fixed Value'],
  'material':                ['Unlimited', 'Options', 'Advanced Formula', 'Formula', 'Fixed Value'],
  'contour':                 ['Unlimited', 'Options', 'Advanced Formula', 'Formula', 'Fixed Value'],
  'style':                   ['Unlimited', 'Options', 'Advanced Formula', 'Formula', 'Fixed Value']
};

function normHeader(s) {
  return String(s || '').trim().toLowerCase().replace(/[\s_-]+/g, ' ').replace(/[^\w ]/g, '');
}

function getHeaderMap(sheet) {
  const lastCol = sheet.getLastColumn();
  const headers = sheet.getRange(1, 1, 1, lastCol).getValues()[0];
  const map = {};
  headers.forEach((h, i) => {
    const n = normHeader(h);
    if (n) map[n] = i + 1; // 1-based column index
  });
  return map;
}

function findColumn(headerMap, aliases) {
  for (const alias of aliases) {
    const col = headerMap[normHeader(alias)];
    if (col) return col;
  }
  return null;
}

function resolveColumns(sheet) {
  const headerMap = getHeaderMap(sheet);
  const cols = {};
  for (const key in FIELDS) {
    cols[key] = findColumn(headerMap, FIELDS[key]);
  }
  return cols;
}

/**
 * Applies every static dropdown, and seeds the cascading Data type dropdown
 * for whatever Parameter type values already exist. Run manually after
 * installing, and again any time you add/rename/reorder columns.
 */
function setupAllDropdowns() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sheet = ss.getSheetByName(DATA_SHEET_NAME);
  if (!sheet) throw new Error('Sheet "' + DATA_SHEET_NAME + '" not found.');

  const cols = resolveColumns(sheet);

  for (const key in STATIC_OPTIONS) {
    const col = cols[key];
    if (!col) continue; // header not present on this sheet — skip quietly
    applyStaticList(sheet, col, STATIC_OPTIONS[key]);
  }

  if (cols.dataType && cols.paramType) {
    const lastRow = Math.max(sheet.getLastRow(), 2);
    for (let row = 2; row <= lastRow; row++) {
      applyDataTypeValidation(sheet, row, cols);
    }
  }
}

function applyStaticList(sheet, col, options) {
  const rule = SpreadsheetApp.newDataValidation()
    .requireValueInList(options, true)
    .setAllowInvalid(false)
    .build();
  sheet.getRange(2, col, LAST_SETUP_ROW - 1, 1).setDataValidation(rule);
}

function applyDataTypeValidation(sheet, row, cols) {
  const dataTypeCell = sheet.getRange(row, cols.dataType);
  const paramType = String(sheet.getRange(row, cols.paramType).getValue()).trim();

  if (!paramType) {
    dataTypeCell.clearDataValidations();
    dataTypeCell.setNote(null);
    return;
  }

  const validTypes = TYPE_DATATYPE_MAP[paramType.toLowerCase()];
  if (!validTypes) {
    dataTypeCell.clearDataValidations();
    dataTypeCell.setNote('Unknown Parameter type "' + paramType + '" — not in TYPE_DATATYPE_MAP in the Apps Script.');
    return;
  }

  const rule = SpreadsheetApp.newDataValidation()
    .requireValueInList(validTypes, true)
    .setAllowInvalid(false)
    .build();
  dataTypeCell.setDataValidation(rule);
  dataTypeCell.setNote(null);

  // If the row already had a Data type value no longer valid for the newly
  // selected Parameter type, clear it rather than leave a silently-invalid
  // combination. A same-value drag (Float -> Float down many rows) never
  // hits this, since the existing value stays in validTypes.
  const current = String(dataTypeCell.getValue()).trim();
  if (current && validTypes.indexOf(current) === -1) {
    dataTypeCell.setValue('');
  }
}

function onEdit(e) {
  const sheet = e.range.getSheet();
  if (sheet.getName() !== DATA_SHEET_NAME) return;

  const startRow = Math.max(e.range.getRow(), 2); // never touch the header row
  const endRow = e.range.getRow() + e.range.getNumRows() - 1;
  if (startRow > endRow) return;

  const cols = resolveColumns(sheet);
  if (!cols.paramType || !cols.dataType) return;

  // Only the Data type dropdown needs live recomputation — it's the only
  // cascading one. Static dropdowns were already applied to rows 2:2000 by
  // setupAllDropdowns() and don't need re-applying on every edit.
  const startCol = e.range.getColumn();
  const endCol = startCol + e.range.getNumColumns() - 1;
  const touchedParamType = cols.paramType >= startCol && cols.paramType <= endCol;
  if (!touchedParamType) return;

  for (let row = startRow; row <= endRow; row++) {
    applyDataTypeValidation(sheet, row, cols);
  }
}
